# Generated by Django 4.2.2 on 2024-09-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_verify_code_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='457938', max_length=6, verbose_name='Код верификации'),
        ),
    ]
