# Generated by Django 4.2.2 on 2024-09-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_payment_link_payment_session_id_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счет')], max_length=10, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='602895', max_length=6, verbose_name='Код верификации'),
        ),
    ]
