# Generated by Django 4.2.2 on 2024-09-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_payment_payment_method_alter_user_verify_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='link',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='session_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_price_id',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_product_id',
            field=models.CharField(default='default_product_id', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(default='default_session_id', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='306479', max_length=6, verbose_name='Код верификации'),
        ),
    ]
