# Generated by Django 4.2.2 on 2024-09-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_payment_amount_remove_payment_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='614023', max_length=6, verbose_name='Код верификации'),
        ),
    ]
