# Generated by Django 4.2.2 on 2024-09-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_verify_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='957368', max_length=6, verbose_name='Код верификации'),
        ),
    ]
