# Generated by Django 4.2.2 on 2024-09-18 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_course_price'),
        ('users', '0020_alter_payment_user_alter_user_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_course', to='lms.course', verbose_name='Оплаченный курс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='578164', max_length=6, verbose_name='Код верификации'),
        ),
    ]
