# Generated by Django 4.2.2 on 2024-09-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_payment_course_alter_user_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('success', 'Оплачено'), ('failed', 'Ошибка')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='398520', max_length=6, verbose_name='Код верификации'),
        ),
    ]
