# Generated by Django 4.2.2 on 2024-10-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='736209', max_length=6, verbose_name='Код верификации'),
        ),
    ]
