# Generated by Django 4.2.2 on 2024-09-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='lesson',
            field=models.ManyToManyField(related_name='course_lessons', to='lms.lesson', verbose_name='Уроки'),
        ),
    ]
