# Generated by Django 4.2.2 on 2024-10-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_course_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
